// Generated by shaders/GenerateToneShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_tonemap_hlsl_vert[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_0 : TEXCOORD0;
};


#line 11
ToneVertex_0 toneVertexMain(uint index_0 : SV_VertexID)
{
    float _S1 = float((index_0 << int(1)) & 2U);

#line 13
    float _S2 = float(index_0 & 2U);

#line 12
    ToneVertex_0 output_0;

    output_0.position_0 = float4(float2(_S1, _S2) * 2.0f - 1.0f, 0.0f, 1.0f);



    output_0.uv_0 = float2(_S1, 1.0f - _S2);

    return output_0;
}

)NEXORA_TONE";
inline constexpr char scene_tonemap_hlsl_frag[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 93 "core"
Texture2D<float4 > hdrScene_texture_0 : register(t0);


#line 1188 "hlsl.meta.slang"
SamplerState hdrScene_sampler_0 : register(s0);


#line 2 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneParameters_0
{
    float4 settings_0;
};


#line 6
cbuffer tone_0 : register(b0)
{
    ToneParameters_0 tone_0;
}

#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_0)
{
    float3 color_0 = max(hdrColor_0, (float3)0.0f);
    return saturate(color_0 * (2.50999999046325684f * color_0 + 0.02999999932944775f) / (color_0 * (2.43000006675720215f * color_0 + 0.5899999737739563f) + 0.14000000059604645f));
}


#line 11
float3 NexoraLinearToSrgb_0(float3 linearColor_0)
{
    float3 color_1 = max(linearColor_0, (float3)0.0f);


    return lerp(color_1 * 12.92000007629394531f, 1.0549999475479126f * pow(color_1, (float3)0.4166666567325592f) - 0.05499999970197678f, step((float3)0.00313080009073019f, color_1));
}


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_0 : TEXCOORD0;
};


#line 23
float4 toneFragmentMain(ToneVertex_0 input_0) : SV_TARGET
{

#line 24
    float3 color_2 = NexoraAcesApproximate_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_0, 0.0f).xyz * tone_0.settings_0.x);

#line 24
    float3 color_3;
    if((tone_0.settings_0.y) > 0.5f)
    {

#line 25
        color_3 = NexoraLinearToSrgb_0(color_2);

#line 25
    }
    else
    {

#line 25
        color_3 = color_2;

#line 25
    }
    return float4(color_3, 1.0f);
}

)NEXORA_TONE";
} // namespace Nexora::Presentation
// clang-format on
