// Generated by shaders/GenerateToneShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_tonemap_hlsl_vert[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_0 : TEXCOORD0;
};


#line 11
ToneVertex_0 toneVertexMain(float2 position_1 : POSITION, float2 uv_1 : TEXCOORD0)
{

    ToneVertex_0 output_0;
    output_0.position_0 = float4(position_1, 0.0f, 1.0f);



    output_0.uv_0 = uv_1;

    return output_0;
}

)NEXORA_TONE";
inline constexpr char scene_tonemap_hlsl_frag[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 93 "core"
Texture2D<float4 > hdrScene_texture_0 : register(t0);


#line 1188 "hlsl.meta.slang"
SamplerState hdrScene_sampler_0 : register(s0);


#line 2 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneParameters_0
{
    float4 settings_0;
    float4 bloom_0;
    float4 focus_0;
    float4 antiAlias_0;
    float4 occlusion_0;
};


#line 6
cbuffer tone_0 : register(b0)
{
    ToneParameters_0 tone_0;
}

#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_0)
{
    float3 color_0 = max(hdrColor_0, (float3)0.0f);
    return saturate(color_0 * (2.50999999046325684f * color_0 + 0.02999999932944775f) / (color_0 * (2.43000006675720215f * color_0 + 0.5899999737739563f) + 0.14000000059604645f));
}


#line 23 "Engine/Presentation/shaders/scene_tonemap.slang"
float displayLuma_0(float3 hdr_0)
{

#line 24
    return dot(NexoraAcesApproximate_0(hdr_0 * tone_0.settings_0.x), float3(0.29899999499320984f, 0.58700001239776611f, 0.11400000005960464f));
}


#line 26
float3 filterEdges_0(float2 uv_0, float3 center_0)
{

#line 27
    float2 pixel_0 = tone_0.antiAlias_0.xy;

#line 32
    float lnw_0 = displayLuma_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + float2(-1.0f, -1.0f) * pixel_0, 0.0f).xyz);

#line 32
    float lne_0 = displayLuma_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + float2(1.0f, -1.0f) * pixel_0, 0.0f).xyz);

#line 32
    float lsw_0 = displayLuma_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + float2(-1.0f, 1.0f) * pixel_0, 0.0f).xyz);

#line 32
    float lse_0 = displayLuma_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + pixel_0, 0.0f).xyz);
    float lm_0 = displayLuma_0(center_0);
    float _S1 = min(lm_0, min(min(lnw_0, lne_0), min(lsw_0, lse_0)));
    float _S2 = max(lm_0, max(max(lnw_0, lne_0), max(lsw_0, lse_0)));
    if((_S2 - _S1) <= (max(0.03119999915361404f, _S2 * 0.125f)))
    {

#line 36
        return center_0;
    }

#line 37
    float _S3 = lnw_0 + lne_0;

#line 37
    float _S4 = - (_S3 - (lsw_0 + lse_0));

#line 37
    float _S5 = lnw_0 + lsw_0 - (lne_0 + lse_0);

    float2 direction_0 = clamp(float2(_S4, _S5) / (min(abs(_S4), abs(_S5)) + max((_S3 + lsw_0 + lse_0) * 0.03125f, 0.0078125f)), float2((int2)int(-8)), float2((int2)int(8))) * pixel_0;
    float3 a_0 = 0.5f * (hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + direction_0 * -0.1666666716337204f, 0.0f).xyz + hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + direction_0 * 0.1666666716337204f, 0.0f).xyz);

    float3 b_0 = 0.5f * a_0 + 0.25f * (hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + direction_0 * -0.5f, 0.0f).xyz + hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, uv_0 + direction_0 * 0.5f, 0.0f).xyz);

    float lb_0 = displayLuma_0(b_0);

#line 44
    bool _S6;
    if(lb_0 < _S1)
    {

#line 45
        _S6 = true;

#line 45
    }
    else
    {

#line 45
        _S6 = lb_0 > _S2;

#line 45
    }

#line 45
    float3 _S7;

#line 45
    if(_S6)
    {

#line 45
        _S7 = a_0;

#line 45
    }
    else
    {

#line 45
        _S7 = b_0;

#line 45
    }

#line 45
    return _S7;
}

float3 contactPosition_0(float2 uv_1, float distance_0)
{

    return normalize(float3((uv_1.x * 2.0f - 1.0f) * (tone_0.antiAlias_0.y / tone_0.antiAlias_0.x) * tone_0.occlusion_0.w, (1.0f - uv_1.y * 2.0f) * tone_0.occlusion_0.w, -1.0f)) * distance_0;
}


#line 53
float contactVisibility_0(float2 uv_2, float distance_1)
{

#line 53
    bool _S8;

    if(distance_1 <= 0.0f)
    {

#line 55
        _S8 = true;

#line 55
    }
    else
    {

#line 55
        _S8 = distance_1 >= 64.0f;

#line 55
    }

#line 55
    if(_S8)
    {

#line 55
        return 1.0f;
    }

#line 56
    float3 center_1 = contactPosition_0(uv_2, distance_1);
    float2 pixel_1 = tone_0.antiAlias_0.xy;
    float _S9 = pixel_1.x;

#line 58
    float2 _S10 = float2(_S9, 0.0f);

#line 58
    float2 _S11 = uv_2 - _S10;

#line 58
    float3 left_0 = contactPosition_0(_S11, hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, _S11, 0.0f).w);
    float2 _S12 = uv_2 + _S10;

#line 59
    float3 right_0 = contactPosition_0(_S12, hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, _S12, 0.0f).w);
    float _S13 = pixel_1.y;

#line 60
    float2 _S14 = float2(0.0f, _S13);

#line 60
    float2 _S15 = uv_2 - _S14;

#line 60
    float3 up_0 = contactPosition_0(_S15, hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, _S15, 0.0f).w);
    float2 _S16 = uv_2 + _S14;

#line 61
    float3 down_0 = contactPosition_0(_S16, hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, _S16, 0.0f).w);
    float _S17 = center_1.z;

#line 62
    float3 dx_0;

#line 62
    if((abs(left_0.z - _S17)) < (abs(right_0.z - _S17)))
    {

#line 62
        dx_0 = center_1 - left_0;

#line 62
    }
    else
    {

#line 62
        dx_0 = right_0 - center_1;

#line 62
    }

#line 62
    float3 dy_0;
    if((abs(up_0.z - _S17)) < (abs(down_0.z - _S17)))
    {

#line 63
        dy_0 = center_1 - up_0;

#line 63
    }
    else
    {

#line 63
        dy_0 = down_0 - center_1;

#line 63
    }
    float3 normal_0 = cross(dx_0, dy_0);
    if((dot(normal_0, normal_0)) < 1.00000001335143196e-10f)
    {

#line 65
        return 1.0f;
    }

#line 66
    float3 normal_1 = normalize(normal_0);

#line 66
    float3 normal_2;
    if((dot(normal_1, - center_1)) < 0.0f)
    {

#line 67
        normal_2 = - normal_1;

#line 67
    }
    else
    {

#line 67
        normal_2 = normal_1;

#line 67
    }
    float2  _S18[int(6)] = { float2(1.0f, 0.0f), float2(0.5f, 0.86602497100830078f), float2(-0.5f, 0.86602497100830078f), float2(-1.0f, 0.0f), float2(-0.5f, -0.86602497100830078f), float2(0.5f, -0.86602497100830078f) };

    float radius_0 = tone_0.occlusion_0.y;

    float2 _S19 = min(float2(_S9 / _S13, 1.0f) * radius_0 / (2.0f * max(abs(_S17), 0.10000000149011612f) * tone_0.occlusion_0.w), pixel_1 * 32.0f);

#line 72
    uint i_0 = 0U;

#line 72
    float blocked_0 = 0.0f;

    [unroll]
    for(;;)
    {

#line 74
        if(i_0 < 12U)
        {
        }
        else
        {

#line 74
            break;
        }

#line 75
        float2 _S20 = _S18[i_0 % 6U] * _S19;

#line 75
        float _S21;

#line 75
        if(i_0 < 6U)
        {

#line 75
            _S21 = 0.5f;

#line 75
        }
        else
        {

#line 75
            _S21 = 1.0f;

#line 75
        }

#line 75
        float2 sampleUv_0 = uv_2 + _S20 * _S21;

        if(all(sampleUv_0 > 0.0f))
        {

#line 77
            _S8 = all(sampleUv_0 < 1.0f);

#line 77
        }
        else
        {

#line 77
            _S8 = false;

#line 77
        }

#line 77
        float blocked_1;

#line 77
        if(_S8)
        {

#line 78
            float tapDistance_0 = hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, sampleUv_0, 0.0f).w;
            if(tapDistance_0 > 0.0f)
            {

#line 80
                float3 delta_0 = contactPosition_0(sampleUv_0, tapDistance_0) - center_1;
                float lengthSquared_0 = dot(delta_0, delta_0);

#line 81
                bool _S22;
                if(lengthSquared_0 > 9.99999997475242708e-07f)
                {

#line 82
                    _S22 = lengthSquared_0 < (radius_0 * radius_0);

#line 82
                }
                else
                {

#line 82
                    _S22 = false;

#line 82
                }

#line 82
                if(_S22)
                {

#line 82
                    blocked_1 = blocked_0 + saturate((dot(normal_2, delta_0) - tone_0.occlusion_0.z) / sqrt(lengthSquared_0)) * (1.0f - lengthSquared_0 / (radius_0 * radius_0));

#line 82
                }
                else
                {

#line 82
                    blocked_1 = blocked_0;

#line 82
                }

#line 79
            }
            else
            {

#line 79
                blocked_1 = blocked_0;

#line 79
            }

#line 77
        }
        else
        {

#line 77
            blocked_1 = blocked_0;

#line 77
        }

#line 74
        i_0 = i_0 + 1U;

#line 74
        blocked_0 = blocked_1;

#line 74
    }

#line 89
    return saturate(1.0f - tone_0.occlusion_0.x * (1.0f - smoothstep(32.0f, 64.0f, distance_1)) * blocked_0 / 6.0f);
}


#line 16 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraExtractBloom_0(float3 hdrColor_1, float threshold_0)
{
    float3 color_1 = max(hdrColor_1, (float3)0.0f);
    float _S23 = max(max(color_1.x, color_1.y), color_1.z);
    return color_1 * max(_S23 - max(threshold_0, 0.0f), 0.0f) / max(_S23, 0.00009999999747379f);
}

float3 NexoraApplyBloom_0(float3 hdrColor_2, float3 bloomColor_0, float intensity_0)
{
    float3 _S24 = (float3)0.0f;

#line 25
    return max(hdrColor_2, _S24) + max(bloomColor_0, _S24) * max(intensity_0, 0.0f);
}


#line 19 "Shaders/Nexora/Common/Color.slang"
float NexoraRec709Luminance_0(float3 linearColor_0)
{
    return dot(linearColor_0, float3(0.2125999927520752f, 0.71520000696182251f, 0.07220000028610229f));
}


#line 28 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraApplyColorGrade_0(float3 color_2, float3 lift_0, float3 gain_0, float saturation_0, float contrast_0)
{

    float3 _S25 = (float3)0.0f;

#line 31
    float3 graded_0 = max(color_2 + lift_0, _S25) * max(gain_0, _S25);
    float luminance_0 = NexoraRec709Luminance_0(graded_0);

    return max((lerp(float3(luminance_0, luminance_0, luminance_0), graded_0, (float3)saturation_0) - 0.5f) * contrast_0 + 0.5f, _S25);
}


#line 11 "Shaders/Nexora/Common/Color.slang"
float3 NexoraLinearToSrgb_0(float3 linearColor_1)
{
    float3 color_3 = max(linearColor_1, (float3)0.0f);


    return lerp(color_3 * 12.92000007629394531f, 1.0549999475479126f * pow(color_3, (float3)0.4166666567325592f) - 0.05499999970197678f, step((float3)0.00313080009073019f, color_3));
}


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_3 : TEXCOORD0;
};


#line 92
float4 toneFragmentMain(ToneVertex_0 input_0) : SV_TARGET
{

#line 93
    float4 _S26 = hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_3, 0.0f);

#line 93
    float3 hdr_1;
    if((tone_0.antiAlias_0.z) > 0.5f)
    {

#line 94
        hdr_1 = filterEdges_0(input_0.uv_3, _S26.xyz);

#line 94
    }
    else
    {

#line 94
        hdr_1 = _S26.xyz;

#line 94
    }

#line 94
    bool _S27;
    if((tone_0.focus_0.y) > 0.0f)
    {

#line 95
        _S27 = (_S26.w) > 0.0f;

#line 95
    }
    else
    {

#line 95
        _S27 = false;

#line 95
    }

#line 95
    float3 color_4;

#line 95
    uint i_1;

#line 95
    if(_S27)
    {

#line 96
        float _S28 = _S26.w;

#line 96
        float coc_0 = saturate(abs(_S28 - tone_0.focus_0.x) / max(_S28, 0.00100000004749745f) * tone_0.focus_0.y);
        if(coc_0 > 0.05000000074505806f)
        {

#line 98
            float2  _S29[int(12)] = { float2(-1.0f, 0.0f), float2(1.0f, 0.0f), float2(0.0f, -1.0f), float2(0.0f, 1.0f), float2(-0.7070000171661377f, -0.7070000171661377f), float2(0.7070000171661377f, -0.7070000171661377f), float2(-0.7070000171661377f, 0.7070000171661377f), float2(0.7070000171661377f, 0.7070000171661377f), float2(-0.34999999403953552f, -0.34999999403953552f), float2(0.34999999403953552f, -0.34999999403953552f), float2(-0.34999999403953552f, 0.34999999403953552f), float2(0.34999999403953552f, 0.34999999403953552f) };

#line 98
            i_1 = 0U;

#line 98
            color_4 = hdr_1;

#line 98
            float weights_0 = 1.0f;

#line 103
            [unroll]
            for(;;)
            {

#line 103
                if(i_1 < 12U)
                {
                }
                else
                {

#line 103
                    break;
                }

#line 104
                float4 _S30 = hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_3 + _S29[i_1] * tone_0.focus_0.zw * coc_0, 0.0f);

                float weight_0 = saturate(1.0f - abs(_S30.w - _S28) / max(1.0f, _S28 * 0.25f));
                float3 sum_0 = color_4 + _S30.xyz * weight_0;
                float weights_1 = weights_0 + weight_0;

#line 103
                i_1 = i_1 + 1U;

#line 103
                color_4 = sum_0;

#line 103
                weights_0 = weights_1;

#line 103
            }

#line 103
            hdr_1 = color_4 / weights_0;

#line 97
        }
        else
        {

#line 97
        }

#line 95
    }
    else
    {

#line 95
    }

#line 113
    if((tone_0.occlusion_0.x) > 0.0f)
    {

#line 113
        hdr_1 = hdr_1 * lerp(contactVisibility_0(input_0.uv_3, _S26.w), 1.0f, saturate(max(_S26.x, max(_S26.y, _S26.z)) - 1.0f));

#line 113
    }
    else
    {

#line 113
    }

#line 119
    if((tone_0.bloom_0.x) > 0.0f)
    {

#line 120
        float2 _S31 = tone_0.bloom_0.zw;

        float2  _S32[int(12)] = { float2(-1.0f, 0.0f), float2(1.0f, 0.0f), float2(0.0f, -1.0f), float2(0.0f, 1.0f), float2(-0.5f, -0.5f), float2(0.5f, -0.5f), float2(-0.5f, 0.5f), float2(0.5f, 0.5f), float2(-0.25f, 0.0f), float2(0.25f, 0.0f), float2(0.0f, -0.25f), float2(0.0f, 0.25f) };


        float3 _S33 = float3(0.0f, 0.0f, 0.0f);

#line 125
        i_1 = 0U;

#line 125
        color_4 = _S33;
        [unroll]
        for(;;)
        {

#line 126
            if(i_1 < 12U)
            {
            }
            else
            {

#line 126
                break;
            }

#line 127
            float3 glow_0 = color_4 + NexoraExtractBloom_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_3 + _S32[i_1] * _S31, 0.0f).xyz, tone_0.bloom_0.y) / 12.0f;

#line 126
            i_1 = i_1 + 1U;

#line 126
            color_4 = glow_0;

#line 126
        }

#line 126
        hdr_1 = NexoraApplyBloom_0(hdr_1, color_4, tone_0.bloom_0.x);

#line 119
    }
    else
    {

#line 119
    }

#line 132
    float3 color_5 = saturate(NexoraApplyColorGrade_0(NexoraAcesApproximate_0(hdr_1 * tone_0.settings_0.x), float3((int3)int(0)), float3((int3)int(1)), tone_0.settings_0.z, tone_0.settings_0.w));
    if((tone_0.settings_0.y) > 0.5f)
    {

#line 133
        color_4 = NexoraLinearToSrgb_0(color_5);

#line 133
    }
    else
    {

#line 133
        color_4 = color_5;

#line 133
    }
    return float4(color_4, 1.0f);
}

)NEXORA_TONE";
} // namespace Nexora::Presentation
// clang-format on
