// Generated by shaders/GeneratePbrShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_pbr_hlsl_vert[] = R"NEXORA_PBR(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 13873 "hlsl.meta.slang"
struct _MatrixStorage_float4x4natural_0
{
    float4  data_0[int(4)];
};


#line 9 "Engine/Presentation/shaders/scene_pbr.slang"
struct SceneConstants_natural_0
{
    _MatrixStorage_float4x4natural_0 mvp_0;
    float4 lightDirection_0;
    float4 lightColor_0;
    float4 legacyColor_0;
};


#line 14
cbuffer scene_0 : register(b0)
{
    SceneConstants_natural_0 scene_0;
}

#line 3 "Shaders/Nexora/Common/Math.slang"
float3 NexoraSafeNormalize_0(float3 value_0)
{
    float lengthSquared_0 = dot(value_0, value_0);

#line 5
    float3 _S1;
    if(lengthSquared_0 > 9.999999960041972e-13f)
    {

#line 6
        _S1 = value_0 * rsqrt(lengthSquared_0);

#line 6
    }
    else
    {

#line 6
        _S1 = float3(0.0f, 0.0f, 0.0f);

#line 6
    }

#line 6
    return _S1;
}


#line 69 "Engine/Presentation/shaders/scene_pbr.slang"
float3 geometryDirection_0(float3 value_1)
{
    float _S2 = max(max(abs(value_1.x), abs(value_1.y)), abs(value_1.z));

#line 71
    float3 _S3;
    if(_S2 > 0.0f)
    {

#line 72
        _S3 = NexoraSafeNormalize_0(value_1 / _S2);

#line 72
    }
    else
    {

#line 72
        _S3 = float3(0.0f, 0.0f, 0.0f);

#line 72
    }

#line 72
    return _S3;
}


#line 59
struct VertexOutput_0
{
    float4 position_0 : SV_Position;
    float3 worldPosition_0 : TEXCOORD0;
    float3 normal_0 : TEXCOORD1;
    float4 tangent_0 : TEXCOORD2;
    float2 uv_0 : TEXCOORD3;
    float4 color_0 : TEXCOORD4;
};


#line 45
struct VertexInput_0
{
    float3 position_1 : POSITION;
    float3 normal_1 : NORMAL;
    float2 uv_1 : TEXCOORD0;
    float4 model0_0 : INSTANCE_MODEL0;
    float4 model1_0 : INSTANCE_MODEL1;
    float4 model2_0 : INSTANCE_MODEL2;
    float4 normal0_0 : INSTANCE_NORMAL0;
    float4 normal1_0 : INSTANCE_NORMAL1;
    float4 normal2_0 : INSTANCE_NORMAL2;
    float4 color_1 : INSTANCE_COLOR;
    float4 tangent_1 : TANGENT;
};


#line 75
VertexOutput_0 pbrVertexMain(VertexInput_0 input_0)
{

    float4 p_0 = float4(input_0.position_1, 1.0f);

#line 77
    VertexOutput_0 output_0;

    float3 _S4 = float3(dot(input_0.model0_0, p_0), dot(input_0.model1_0, p_0), dot(input_0.model2_0, p_0));

#line 79
    output_0.worldPosition_0 = _S4;
    output_0.position_0 = mul(float4x4(float4x4(scene_0.mvp_0.data_0[int(0)][int(0)], scene_0.mvp_0.data_0[int(0)][int(1)], scene_0.mvp_0.data_0[int(0)][int(2)], scene_0.mvp_0.data_0[int(0)][int(3)], scene_0.mvp_0.data_0[int(1)][int(0)], scene_0.mvp_0.data_0[int(1)][int(1)], scene_0.mvp_0.data_0[int(1)][int(2)], scene_0.mvp_0.data_0[int(1)][int(3)], scene_0.mvp_0.data_0[int(2)][int(0)], scene_0.mvp_0.data_0[int(2)][int(1)], scene_0.mvp_0.data_0[int(2)][int(2)], scene_0.mvp_0.data_0[int(2)][int(3)], scene_0.mvp_0.data_0[int(3)][int(0)], scene_0.mvp_0.data_0[int(3)][int(1)], scene_0.mvp_0.data_0[int(3)][int(2)], scene_0.mvp_0.data_0[int(3)][int(3)])), float4(_S4, 1.0f));



    float3 n_0 = geometryDirection_0(input_0.normal_1);
    float3 _S5 = geometryDirection_0(float3(dot(input_0.normal0_0.xyz, n_0), dot(input_0.normal1_0.xyz, n_0), dot(input_0.normal2_0.xyz, n_0)));

#line 85
    output_0.normal_0 = _S5;

    float _S6 = max(max(max(abs(input_0.model0_0.x), abs(input_0.model0_0.y)), abs(input_0.model0_0.z)), max(max(max(abs(input_0.model1_0.x), abs(input_0.model1_0.y)), abs(input_0.model1_0.z)), max(max(abs(input_0.model2_0.x), abs(input_0.model2_0.y)), abs(input_0.model2_0.z))));


    float3 t_0 = float3(dot(input_0.model0_0.xyz / _S6, input_0.tangent_1.xyz), dot(input_0.model1_0.xyz / _S6, input_0.tangent_1.xyz), dot(input_0.model2_0.xyz / _S6, input_0.tangent_1.xyz));

#line 95
    output_0.tangent_0 = float4(geometryDirection_0(t_0 - _S5 * dot(_S5, t_0)), input_0.tangent_1.w * input_0.normal0_0.w);
    output_0.uv_0 = input_0.uv_1;
    output_0.color_0 = input_0.color_1;
    return output_0;
}

)NEXORA_PBR";
inline constexpr char scene_pbr_hlsl_frag[] = R"NEXORA_PBR(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 93 "core"
Texture2D<float4 > normalMap_texture_0 : register(t1);


#line 1188 "hlsl.meta.slang"
SamplerState normalMap_sampler_0 : register(s1);


#line 23 "Engine/Presentation/shaders/scene_pbr.slang"
struct _MatrixStorage_float4x4natural_0
{
    float4  data_0[int(4)];
};


#line 27
struct MaterialConstants_natural_0
{
    float4 cameraPosition_0;
    float4 baseColor_0;
    float4 emissionRoughness_0;
    float4 properties_0;
    float4 environment_0;
    _MatrixStorage_float4x4natural_0 lightViewProjection_0;
    float4 shadowSettings_0;
    float4 shadowTint_0;
    float4 lightTint_0;
    float4 ramp_0;
};


#line 29
cbuffer material_0 : register(b1)
{
    MaterialConstants_natural_0 material_0;
}

#line 29
Texture2D<float4 > ormMap_texture_0 : register(t2);


#line 29
SamplerState ormMap_sampler_0 : register(s2);


#line 29
Texture2D<float4 > baseMap_texture_0 : register(t0);


#line 29
SamplerState baseMap_sampler_0 : register(s0);


#line 29
Texture2D<float4 > emissionMap_texture_0 : register(t3);


#line 29
SamplerState emissionMap_sampler_0 : register(s3);


#line 29
Texture2D<float4 > diffuseEnvironment_texture_0 : register(t4);


#line 29
SamplerState diffuseEnvironment_sampler_0 : register(s4);


#line 29
Texture2D<float4 > specularEnvironment_texture_0 : register(t5);


#line 29
SamplerState specularEnvironment_sampler_0 : register(s5);


#line 29
Texture2D<float4 > brdfIntegration_texture_0 : register(t6);


#line 29
SamplerState brdfIntegration_sampler_0 : register(s6);


#line 9
struct SceneConstants_natural_0
{
    _MatrixStorage_float4x4natural_0 mvp_0;
    float4 lightDirection_0;
    float4 lightColor_0;
    float4 legacyColor_0;
};


#line 14
cbuffer scene_0 : register(b0)
{
    SceneConstants_natural_0 scene_0;
}

#line 14
Texture2D<float4 > directionalShadow_texture_0 : register(t7);


#line 14
SamplerState directionalShadow_sampler_0 : register(s7);


#line 3 "Shaders/Nexora/Common/Math.slang"
float3 NexoraSafeNormalize_0(float3 value_0)
{
    float lengthSquared_0 = dot(value_0, value_0);

#line 5
    float3 _S1;
    if(lengthSquared_0 > 9.999999960041972e-13f)
    {

#line 6
        _S1 = value_0 * rsqrt(lengthSquared_0);

#line 6
    }
    else
    {

#line 6
        _S1 = float3(0.0f, 0.0f, 0.0f);

#line 6
    }

#line 6
    return _S1;
}


#line 21 "Shaders/Nexora/Common/Pbr.slang"
float3 NexoraDecodeTangentNormal_0(float3 encodedNormal_0, float3 tangent_0, float3 bitangent_0, float3 geometricNormal_0)
{

    float3 tangentNormal_0 = encodedNormal_0 * 2.0f - 1.0f;



    return NexoraSafeNormalize_0(tangentNormal_0.x * NexoraSafeNormalize_0(tangent_0) + tangentNormal_0.y * NexoraSafeNormalize_0(bitangent_0) + tangentNormal_0.z * NexoraSafeNormalize_0(geometricNormal_0));
}


#line 69 "Engine/Presentation/shaders/scene_pbr.slang"
float3 geometryDirection_0(float3 value_1)
{
    float _S2 = max(max(abs(value_1.x), abs(value_1.y)), abs(value_1.z));

#line 71
    float3 _S3;
    if(_S2 > 0.0f)
    {

#line 72
        _S3 = NexoraSafeNormalize_0(value_1 / _S2);

#line 72
    }
    else
    {

#line 72
        _S3 = float3(0.0f, 0.0f, 0.0f);

#line 72
    }

#line 72
    return _S3;
}


#line 39
float2 environmentUv_0(float3 direction_0)
{
    return float2((atan2(direction_0.z, direction_0.x) + material_0.environment_0.y) / 6.28318548202514648f + 0.5f, acos(clamp(direction_0.y, -1.0f, 1.0f)) / 3.14159274101257324f);
}


#line 3 "Shaders/Nexora/Common/Shadow.slang"
float NexoraApplyShadowBias_0(float receiverDepth_0, float normalBias_0, float slopeBias_0, float nDotL_0)
{


    return receiverDepth_0 - max(normalBias_0, 0.0f) - (1.0f - saturate(nDotL_0)) * max(slopeBias_0, 0.0f);
}

float NexoraEvaluatePcf4_0(float receiverDepth_1, float4 shadowDepths_0, float bias_0)
{

    return dot(step((float4)(receiverDepth_1 - max(bias_0, 0.0f)), shadowDepths_0), float4(0.25f, 0.25f, 0.25f, 0.25f));
}


#line 104 "Engine/Presentation/shaders/scene_pbr.slang"
float shadowVisibility_0(float3 position_0, float3 normal_0, float3 light_0)
{

#line 105
    if((material_0.shadowSettings_0.z) == 0.0f)
    {

#line 105
        return 1.0f;
    }

#line 106
    float4 projected_0 = mul(float4x4(float4x4(material_0.lightViewProjection_0.data_0[int(0)][int(0)], material_0.lightViewProjection_0.data_0[int(0)][int(1)], material_0.lightViewProjection_0.data_0[int(0)][int(2)], material_0.lightViewProjection_0.data_0[int(0)][int(3)], material_0.lightViewProjection_0.data_0[int(1)][int(0)], material_0.lightViewProjection_0.data_0[int(1)][int(1)], material_0.lightViewProjection_0.data_0[int(1)][int(2)], material_0.lightViewProjection_0.data_0[int(1)][int(3)], material_0.lightViewProjection_0.data_0[int(2)][int(0)], material_0.lightViewProjection_0.data_0[int(2)][int(1)], material_0.lightViewProjection_0.data_0[int(2)][int(2)], material_0.lightViewProjection_0.data_0[int(2)][int(3)], material_0.lightViewProjection_0.data_0[int(3)][int(0)], material_0.lightViewProjection_0.data_0[int(3)][int(1)], material_0.lightViewProjection_0.data_0[int(3)][int(2)], material_0.lightViewProjection_0.data_0[int(3)][int(3)])), float4(position_0, 1.0f));
    float _S4 = projected_0.w;

#line 107
    if(_S4 <= 0.0f)
    {

#line 107
        return 1.0f;
    }

#line 108
    float3 ndc_0 = projected_0.xyz / _S4;
    float2 uv_0 = ndc_0.xy * float2(0.5f, 0.5f * material_0.shadowSettings_0.w) + 0.5f;

#line 109
    bool _S5;
    if(any(uv_0 < 0.0f))
    {

#line 110
        _S5 = true;

#line 110
    }
    else
    {

#line 110
        _S5 = any(uv_0 > 1.0f);

#line 110
    }

#line 110
    if(_S5)
    {

#line 110
        _S5 = true;

#line 110
    }
    else
    {

#line 110
        _S5 = (ndc_0.z) < 0.0f;

#line 110
    }

#line 110
    if(_S5)
    {

#line 110
        _S5 = true;

#line 110
    }
    else
    {

#line 110
        _S5 = (ndc_0.z) > 1.0f;

#line 110
    }

#line 110
    if(_S5)
    {

#line 110
        return 1.0f;
    }

#line 111
    float2 step_0 = (float2)(material_0.shadowSettings_0.z * 0.5f);

    float _S6 = step_0.x;

#line 113
    float _S7 = - _S6;

#line 113
    float _S8 = step_0.y;

#line 113
    float _S9 = - _S8;

#line 119
    return NexoraEvaluatePcf4_0(NexoraApplyShadowBias_0(ndc_0.z, material_0.shadowSettings_0.x, material_0.shadowSettings_0.y, saturate(dot(normal_0, light_0))), float4(directionalShadow_texture_0.SampleLevel(directionalShadow_sampler_0, uv_0 + float2(_S7, _S9), 0.0f).x, directionalShadow_texture_0.SampleLevel(directionalShadow_sampler_0, uv_0 + float2(_S6, _S9), 0.0f).x, directionalShadow_texture_0.SampleLevel(directionalShadow_sampler_0, uv_0 + float2(_S7, _S8), 0.0f).x, directionalShadow_texture_0.SampleLevel(directionalShadow_sampler_0, uv_0 + step_0, 0.0f).x), 0.0f);
}


#line 9 "Shaders/Nexora/Common/Math.slang"
float NexoraSaturateDot_0(float3 left_0, float3 right_0)
{
    return saturate(dot(left_0, right_0));
}


#line 19 "Shaders/Nexora/Common/Lighting.slang"
float3 NexoraFresnelSchlick_0(float vDotH_0, float3 reflectanceAtNormal_0)
{

    return reflectanceAtNormal_0 + (1.0f - reflectanceAtNormal_0) * pow(saturate(1.0f - vDotH_0), 5.0f);
}


#line 5
float NexoraDistributionGgx_0(float nDotH_0, float roughness_0)
{
    float _S10 = max(roughness_0 * roughness_0, 0.00249999994412065f);
    float alphaSquared_0 = _S10 * _S10;
    float denominator_0 = nDotH_0 * nDotH_0 * (alphaSquared_0 - 1.0f) + 1.0f;
    return alphaSquared_0 / max(3.14159274101257324f * denominator_0 * denominator_0, 1.00000001168609742e-07f);
}

float NexoraGeometrySchlickGgx_0(float nDotV_0, float roughness_1)
{
    float _S11 = roughness_1 + 1.0f;

#line 15
    float k_0 = _S11 * _S11 * 0.125f;
    return nDotV_0 / max(nDotV_0 * (1.0f - k_0) + k_0, 9.99999997475242708e-07f);
}


#line 26
float3 NexoraEvaluateDirectBrdf_0(float3 normal_1, float3 viewDirection_0, float3 lightDirection_1, float3 albedo_0, float metallic_0, float roughness_2, float3 radiance_0)
{


    float3 n_0 = NexoraSafeNormalize_0(normal_1);
    float3 v_0 = NexoraSafeNormalize_0(viewDirection_0);
    float3 l_0 = NexoraSafeNormalize_0(lightDirection_1);
    float3 h_0 = NexoraSafeNormalize_0(v_0 + l_0);
    float nDotV_1 = NexoraSaturateDot_0(n_0, v_0);
    float nDotL_1 = NexoraSaturateDot_0(n_0, l_0);
    float nDotH_1 = NexoraSaturateDot_0(n_0, h_0);
    float vDotH_1 = NexoraSaturateDot_0(v_0, h_0);

#line 37
    bool _S12;
    if(nDotV_1 <= 0.0f)
    {

#line 38
        _S12 = true;

#line 38
    }
    else
    {

#line 38
        _S12 = nDotL_1 <= 0.0f;

#line 38
    }

#line 38
    if(_S12)
    {

#line 39
        return float3(0.0f, 0.0f, 0.0f);
    }
    float metal_0 = saturate(metallic_0);
    float rough_0 = clamp(roughness_2, 0.05000000074505806f, 1.0f);
    float3 baseColor_1 = saturate(albedo_0);

    float3 fresnel_0 = NexoraFresnelSchlick_0(vDotH_1, lerp(float3(0.03999999910593033f, 0.03999999910593033f, 0.03999999910593033f), baseColor_1, (float3)metal_0));

#line 52
    return ((1.0f - fresnel_0) * (1.0f - metal_0) * baseColor_1 / 3.14159274101257324f + NexoraDistributionGgx_0(nDotH_1, rough_0) * (NexoraGeometrySchlickGgx_0(nDotV_1, rough_0) * NexoraGeometrySchlickGgx_0(nDotL_1, rough_0)) * fresnel_0 / max(4.0f * nDotV_1 * nDotL_1, 9.99999997475242708e-07f)) * radiance_0 * nDotL_1;
}


#line 31 "Shaders/Nexora/Common/Pbr.slang"
float3 NexoraComputePbrF0_0(float3 baseColor_2, float metallic_1)
{

    return lerp(float3(0.03999999910593033f, 0.03999999910593033f, 0.03999999910593033f), saturate(baseColor_2), (float3)saturate(metallic_1));
}

float3 NexoraFresnelSchlickRoughness_0(float nDotV_2, float3 f0_0, float roughness_3)
{
    float _S13 = 1.0f - roughness_3;

    return f0_0 + (max(float3(_S13, _S13, _S13), f0_0) - f0_0) * pow(saturate(1.0f - nDotV_2), 5.0f);
}


#line 14
struct NexoraPbrEnvironment_0
{
    float3 diffuseIrradiance_0;
    float3 prefilteredSpecular_0;
    float2 brdfLut_0;
};


#line 44
float3 NexoraEvaluatePbrIbl_0(float3 normal_2, float3 viewDirection_1, float3 baseColor_3, float metallic_2, float roughness_4, float ao_0, NexoraPbrEnvironment_0 environment_1)
{

#line 51
    float metal_1 = saturate(metallic_2);
    float3 albedo_1 = saturate(baseColor_3);

    float3 fresnel_1 = NexoraFresnelSchlickRoughness_0(NexoraSaturateDot_0(NexoraSafeNormalize_0(normal_2), NexoraSafeNormalize_0(viewDirection_1)), NexoraComputePbrF0_0(albedo_1, metal_1), saturate(roughness_4));

    float _S14 = saturate(ao_0);



    return environment_1.diffuseIrradiance_0 * albedo_1 * ((1.0f - fresnel_1) * (1.0f - metal_1)) * _S14 / 3.14159274101257324f + environment_1.prefilteredSpecular_0 * (fresnel_1 * environment_1.brdfLut_0.x + environment_1.brdfLut_0.y) * _S14;
}


#line 3 "Shaders/Nexora/Common/Stylized.slang"
float NexoraEvaluateStylizedRamp_0(float nDotL_2, float offset_0, float scale_0, float softness_0)
{

    float _S15 = max(softness_0, 0.00009999999747379f);
    return smoothstep(0.5f - _S15, 0.5f + _S15, saturate(nDotL_2 * scale_0 + offset_0));
}


#line 19 "Shaders/Nexora/Common/Color.slang"
float NexoraRec709Luminance_0(float3 linearColor_0)
{
    return dot(linearColor_0, float3(0.2125999927520752f, 0.71520000696182251f, 0.07220000028610229f));
}


#line 10 "Shaders/Nexora/Common/Stylized.slang"
float3 NexoraApplyStylizedResponse_0(float3 lighting_0, float shadowFactor_0, float3 shadowTint_1, float3 lightTint_1, float contrast_0, float saturation_0)
{


    float3 tinted_0 = lighting_0 * lerp(shadowTint_1, lightTint_1, (float3)saturate(shadowFactor_0));
    float3 _S16 = (float3)0.0f;

#line 15
    float luminance_0 = NexoraRec709Luminance_0(max(tinted_0, _S16));

    return max((lerp(float3(luminance_0, luminance_0, luminance_0), tinted_0, (float3)saturation_0) - 0.5f) * contrast_0 + 0.5f, _S16);
}


#line 29 "Shaders/Nexora/Common/Shadow.slang"
float3 NexoraApplyShadowTint_0(float3 lighting_1, float shadowVisibility_1, float3 shadowTint_2)
{

    return lighting_1 * lerp(saturate(shadowTint_2), float3(1.0f, 1.0f, 1.0f), (float3)saturate(shadowVisibility_1));
}


#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_0)
{
    float3 color_0 = max(hdrColor_0, (float3)0.0f);
    return saturate(color_0 * (2.50999999046325684f * color_0 + 0.02999999932944775f) / (color_0 * (2.43000006675720215f * color_0 + 0.5899999737739563f) + 0.14000000059604645f));
}


#line 11
float3 NexoraLinearToSrgb_0(float3 linearColor_1)
{
    float3 color_1 = max(linearColor_1, (float3)0.0f);


    return lerp(color_1 * 12.92000007629394531f, 1.0549999475479126f * pow(color_1, (float3)0.4166666567325592f) - 0.05499999970197678f, step((float3)0.00313080009073019f, color_1));
}


#line 59 "Engine/Presentation/shaders/scene_pbr.slang"
struct VertexOutput_0
{
    float4 position_1 : SV_Position;
    float3 worldPosition_0 : TEXCOORD0;
    float3 normal_3 : TEXCOORD1;
    float4 tangent_1 : TEXCOORD2;
    float2 uv_1 : TEXCOORD3;
    float4 color_2 : TEXCOORD4;
};


#line 3 "Shaders/Nexora/Common/Pbr.slang"
struct NexoraPbrMaterial_0
{
    float3 baseColor_4;
    float metallic_3;
    float roughness_5;
    float3 normal_4;
    float ao_1;
    float3 emission_0;
    float alpha_0;
};


#line 122 "Engine/Presentation/shaders/scene_pbr.slang"
float4 pbrFragmentMain(VertexOutput_0 input_0) : SV_TARGET
{
    float3 n_1 = NexoraSafeNormalize_0(input_0.normal_3);
    float3 t_0 = NexoraSafeNormalize_0(input_0.tangent_1.xyz - n_1 * dot(n_1, input_0.tangent_1.xyz));
    float3 b_0 = NexoraSafeNormalize_0(cross(n_1, t_0)) * input_0.tangent_1.w;

#line 126
    float2 _S17 = input_0.uv_1;
    ;

#line 127
    float3 _S18 = normalMap_texture_0.Sample(normalMap_sampler_0, _S17).xyz;

#line 127
    float3 encoded_0 = _S18;
    encoded_0.xy = (_S18.xy - 0.5f) * material_0.properties_0.z + 0.5f;

#line 128
    float2 _S19 = input_0.uv_1;
    ;

#line 129
    float3 orm_0 = ormMap_texture_0.Sample(ormMap_sampler_0, _S19).xyz;
    NexoraPbrMaterial_0 surface_0;

#line 130
    float2 _S20 = input_0.uv_1;
    ;

#line 131
    surface_0.baseColor_4 = baseMap_texture_0.Sample(baseMap_sampler_0, _S20).xyz * material_0.baseColor_0.xyz * input_0.color_2.xyz;
    surface_0.normal_4 = NexoraDecodeTangentNormal_0(encoded_0, t_0, b_0, n_1);
    surface_0.metallic_3 = saturate(orm_0.z * material_0.properties_0.x);
    surface_0.roughness_5 = saturate(orm_0.y * material_0.emissionRoughness_0.w);
    surface_0.ao_1 = saturate(orm_0.x * material_0.properties_0.y);

#line 135
    float2 _S21 = input_0.uv_1;
    ;

#line 136
    surface_0.emission_0 = emissionMap_texture_0.Sample(emissionMap_sampler_0, _S21).xyz * material_0.emissionRoughness_0.xyz;
    surface_0.alpha_0 = 1.0f;

    NexoraPbrEnvironment_0 environment_2;
    float3 _S22 = float3(0.0f, 0.0f, 0.0f);

#line 140
    environment_2.diffuseIrradiance_0 = _S22;
    environment_2.prefilteredSpecular_0 = _S22;
    environment_2.brdfLut_0 = float2(0.0f, 0.0f);
    float3 viewDirection_2 = geometryDirection_0(material_0.cameraPosition_0.xyz - input_0.worldPosition_0);
    if((material_0.environment_0.x) > 0.0f)
    {

#line 145
        float3 n_2 = geometryDirection_0(surface_0.normal_4);
        float roughness_6 = saturate(surface_0.roughness_5);
        environment_2.diffuseIrradiance_0 = diffuseEnvironment_texture_0.SampleLevel(diffuseEnvironment_sampler_0, environmentUv_0(n_2), 0.0f).xyz * material_0.environment_0.x;

        environment_2.prefilteredSpecular_0 = specularEnvironment_texture_0.SampleLevel(specularEnvironment_sampler_0, environmentUv_0(reflect(- viewDirection_2, n_2)), roughness_6 * material_0.environment_0.z).xyz * material_0.environment_0.x;


        environment_2.brdfLut_0 = brdfIntegration_texture_0.SampleLevel(brdfIntegration_sampler_0, float2(saturate(dot(n_2, viewDirection_2)), roughness_6), 0.0f).xy;

#line 144
    }

#line 155
    float3 light_1 = geometryDirection_0(- scene_0.lightDirection_0.xyz);
    float visibility_0 = shadowVisibility_0(input_0.worldPosition_0, geometryDirection_0(surface_0.normal_4), light_1);
    float3 direct_0 = NexoraEvaluateDirectBrdf_0(surface_0.normal_4, viewDirection_2, light_1, surface_0.baseColor_4, surface_0.metallic_3, surface_0.roughness_5, scene_0.lightColor_0.xyz);

    float3 ambient_0 = NexoraEvaluatePbrIbl_0(surface_0.normal_4, viewDirection_2, surface_0.baseColor_4, surface_0.metallic_3, surface_0.roughness_5, surface_0.ao_1, environment_2);

#line 159
    float3 direct_1;

#line 159
    float3 ambient_1;

    if((material_0.shadowTint_0.w) > 0.5f)
    {



        float3 _S23 = NexoraApplyShadowTint_0(ambient_0, visibility_0, material_0.shadowTint_0.xyz);

#line 166
        direct_1 = NexoraApplyStylizedResponse_0(direct_0, NexoraEvaluateStylizedRamp_0(saturate(dot(geometryDirection_0(surface_0.normal_4), light_1)), material_0.ramp_0.x, material_0.ramp_0.y, material_0.ramp_0.z), material_0.shadowTint_0.xyz, material_0.lightTint_0.xyz, 1.0f, 1.0f);

#line 166
        ambient_1 = _S23;

#line 161
    }
    else
    {

#line 161
        direct_1 = direct_0;

#line 161
        ambient_1 = ambient_0;

#line 161
    }

#line 168
    float3 _S24 = float3((int3)int(0));

#line 168
    float3 color_3 = direct_1 * visibility_0 + ambient_1 + max(surface_0.emission_0, _S24);
    if((material_0.properties_0.w) > 0.5f)
    {

#line 170
        return float4(clamp(color_3, _S24, float3((int3)int(65504))), 1.0f);
    }

#line 171
    float3 color_4 = NexoraAcesApproximate_0(color_3);

#line 171
    float3 color_5;
    if((material_0.cameraPosition_0.w) > 0.5f)
    {

#line 172
        color_5 = NexoraLinearToSrgb_0(color_4);

#line 172
    }
    else
    {

#line 172
        color_5 = color_4;

#line 172
    }

    return float4(color_5, 1.0f);
}

)NEXORA_PBR";
inline constexpr char scene_pbr_hlsl_shadow_frag[] = R"NEXORA_PBR(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 59 "Engine/Presentation/shaders/scene_pbr.slang"
struct VertexOutput_0
{
    float4 position_0 : SV_Position;
    float3 worldPosition_0 : TEXCOORD0;
    float3 normal_0 : TEXCOORD1;
    float4 tangent_0 : TEXCOORD2;
    float2 uv_0 : TEXCOORD3;
    float4 color_0 : TEXCOORD4;
};


#line 101
float4 shadowFragmentMain(VertexOutput_0 input_0) : SV_TARGET
{

#line 102
    return float4(input_0.position_0.z, 0.0f, 0.0f, 1.0f);
}

)NEXORA_PBR";
} // namespace Nexora::Presentation
// clang-format on
