// Generated by shaders/GenerateToneShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_tonemap_metal_vert[] = R"NEXORA_TONE(
#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 11 "Engine/Presentation/shaders/scene_tonemap.slang"
struct toneVertexMain_Result_0
{
    float4 position_0 [[position]];
    float2 uv_0 [[user(TEXCOORD)]];
};


#line 11
struct vertexInput_0
{
    float2 position_1 [[attribute(0)]];
    float2 uv_1 [[attribute(1)]];
};


#line 9
struct ToneVertex_0
{
    float4 position_2;
    float2 uv_2;
};


#line 9
[[vertex]] toneVertexMain_Result_0 toneVertexMain(vertexInput_0 _S1 [[stage_in]])
{



    thread ToneVertex_0 output_0;
    (&output_0)->position_2 = float4(_S1.position_1, 0.0f, 1.0f);



    (&output_0)->uv_2 = _S1.uv_1;

#line 19
    thread toneVertexMain_Result_0 _S2;

#line 19
    (&_S2)->position_0 = output_0.position_2;

#line 19
    (&_S2)->uv_0 = output_0.uv_2;

#line 19
    return _S2;
}

)NEXORA_TONE";
inline constexpr char scene_tonemap_metal_frag[] = R"NEXORA_TONE(
#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_0)
{
    float3 color_0 = max(hdrColor_0, float3(0.0f) );
    return saturate(color_0 * (float3(2.50999999046325684f)  * color_0 + float3(0.02999999932944775f) ) / (color_0 * (float3(2.43000006675720215f)  * color_0 + float3(0.5899999737739563f) ) + float3(0.14000000059604645f) ));
}


#line 2 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneParameters_0
{
    float4 settings_0;
    float4 bloom_0;
    float4 focus_0;
    float4 antiAlias_0;
    float4 occlusion_0;
};


#line 1084 "core"
struct KernelContext_0
{
    texture2d<float, access::sample> hdrScene_texture_0;
    sampler hdrScene_sampler_0;
    ToneParameters_0 constant* tone_0;
};


#line 23 "Engine/Presentation/shaders/scene_tonemap.slang"
float displayLuma_0(float3 hdr_0, KernelContext_0 thread* kernelContext_0)
{

#line 24
    return dot(NexoraAcesApproximate_0(hdr_0 * float3(kernelContext_0->tone_0->settings_0.x) ), float3(0.29899999499320984f, 0.58700001239776611f, 0.11400000005960464f));
}


#line 26
float3 filterEdges_0(float2 uv_0, float3 center_0, KernelContext_0 thread* kernelContext_1)
{

#line 27
    float2 pixel_0 = kernelContext_1->tone_0->antiAlias_0.xy;

    float3 ne_0 = ((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + float2(1.0f, -1.0f) * pixel_0), level((0.0f)))).xyz;
    float3 sw_0 = ((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + float2(-1.0f, 1.0f) * pixel_0), level((0.0f)))).xyz;
    float3 se_0 = ((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + pixel_0), level((0.0f)))).xyz;

#line 31
    float _S1 = displayLuma_0(((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + float2(-1.0f, -1.0f) * pixel_0), level((0.0f)))).xyz, kernelContext_1);

#line 31
    float _S2 = displayLuma_0(ne_0, kernelContext_1);

#line 31
    float _S3 = displayLuma_0(sw_0, kernelContext_1);

#line 31
    float _S4 = displayLuma_0(se_0, kernelContext_1);

#line 31
    float _S5 = displayLuma_0(center_0, kernelContext_1);


    float _S6 = min(_S5, min(min(_S1, _S2), min(_S3, _S4)));
    float _S7 = max(_S5, max(max(_S1, _S2), max(_S3, _S4)));
    if((_S7 - _S6) <= (max(0.03119999915361404f, _S7 * 0.125f)))
    {

#line 36
        return center_0;
    }

#line 37
    float _S8 = _S1 + _S2;

#line 37
    float _S9 = - (_S8 - (_S3 + _S4));

#line 37
    float _S10 = _S1 + _S3 - (_S2 + _S4);

    float2 direction_0 = clamp(float2(_S9, _S10) / float2((min(abs(_S9), abs(_S10)) + max((_S8 + _S3 + _S4) * 0.03125f, 0.0078125f))) , float2(int2(int(-8)) ), float2(int2(int(8)) )) * pixel_0;

#line 39
    float3 _S11 = float3(0.5f) ;
    float3 a_0 = _S11 * (((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + direction_0 * float2(-0.1666666716337204f) ), level((0.0f)))).xyz + ((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + direction_0 * float2(0.1666666716337204f) ), level((0.0f)))).xyz);

    float3 b_0 = _S11 * a_0 + float3(0.25f)  * (((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + direction_0 * float2(-0.5f) ), level((0.0f)))).xyz + ((kernelContext_1->hdrScene_texture_0).sample((kernelContext_1->hdrScene_sampler_0), (uv_0 + direction_0 * float2(0.5f) ), level((0.0f)))).xyz);

#line 42
    float _S12 = displayLuma_0(b_0, kernelContext_1);

#line 42
    bool _S13;


    if(_S12 < _S6)
    {

#line 45
        _S13 = true;

#line 45
    }
    else
    {

#line 45
        _S13 = _S12 > _S7;

#line 45
    }

#line 45
    float3 _S14;

#line 45
    if(_S13)
    {

#line 45
        _S14 = a_0;

#line 45
    }
    else
    {

#line 45
        _S14 = b_0;

#line 45
    }

#line 45
    return _S14;
}

float3 contactPosition_0(float2 uv_1, float distance_0, KernelContext_0 thread* kernelContext_2)
{

    return normalize(float3((uv_1.x * 2.0f - 1.0f) * (kernelContext_2->tone_0->antiAlias_0.y / kernelContext_2->tone_0->antiAlias_0.x) * kernelContext_2->tone_0->occlusion_0.w, (1.0f - uv_1.y * 2.0f) * kernelContext_2->tone_0->occlusion_0.w, -1.0f)) * float3(distance_0) ;
}


#line 53
float contactVisibility_0(float2 uv_2, float distance_1, KernelContext_0 thread* kernelContext_3)
{

#line 53
    bool _S15;

    if(distance_1 <= 0.0f)
    {

#line 55
        _S15 = true;

#line 55
    }
    else
    {

#line 55
        _S15 = distance_1 >= 64.0f;

#line 55
    }

#line 55
    if(_S15)
    {

#line 55
        return 1.0f;
    }

#line 55
    float3 _S16 = contactPosition_0(uv_2, distance_1, kernelContext_3);

    float2 pixel_1 = kernelContext_3->tone_0->antiAlias_0.xy;
    float _S17 = pixel_1.x;

#line 58
    float2 _S18 = float2(_S17, 0.0f);

#line 58
    float2 _S19 = uv_2 - _S18;

#line 58
    float3 _S20 = contactPosition_0(_S19, ((kernelContext_3->hdrScene_texture_0).sample((kernelContext_3->hdrScene_sampler_0), (_S19), level((0.0f)))).w, kernelContext_3);
    float2 _S21 = uv_2 + _S18;

#line 59
    float3 _S22 = contactPosition_0(_S21, ((kernelContext_3->hdrScene_texture_0).sample((kernelContext_3->hdrScene_sampler_0), (_S21), level((0.0f)))).w, kernelContext_3);
    float _S23 = pixel_1.y;

#line 60
    float2 _S24 = float2(0.0f, _S23);

#line 60
    float2 _S25 = uv_2 - _S24;

#line 60
    float3 _S26 = contactPosition_0(_S25, ((kernelContext_3->hdrScene_texture_0).sample((kernelContext_3->hdrScene_sampler_0), (_S25), level((0.0f)))).w, kernelContext_3);
    float2 _S27 = uv_2 + _S24;

#line 61
    float3 _S28 = contactPosition_0(_S27, ((kernelContext_3->hdrScene_texture_0).sample((kernelContext_3->hdrScene_sampler_0), (_S27), level((0.0f)))).w, kernelContext_3);
    float _S29 = _S16.z;

#line 62
    float3 dx_0;

#line 62
    if((abs(_S20.z - _S29)) < (abs(_S22.z - _S29)))
    {

#line 62
        dx_0 = _S16 - _S20;

#line 62
    }
    else
    {

#line 62
        dx_0 = _S22 - _S16;

#line 62
    }

#line 62
    float3 dy_0;
    if((abs(_S26.z - _S29)) < (abs(_S28.z - _S29)))
    {

#line 63
        dy_0 = _S16 - _S26;

#line 63
    }
    else
    {

#line 63
        dy_0 = _S28 - _S16;

#line 63
    }
    float3 normal_0 = cross(dx_0, dy_0);
    if((dot(normal_0, normal_0)) < 1.00000001335143196e-10f)
    {

#line 65
        return 1.0f;
    }

#line 66
    float3 normal_1 = normalize(normal_0);

#line 66
    float3 normal_2;
    if((dot(normal_1, - _S16)) < 0.0f)
    {

#line 67
        normal_2 = - normal_1;

#line 67
    }
    else
    {

#line 67
        normal_2 = normal_1;

#line 67
    }
    array<float2, int(6)> _S30 = { { float2(1.0f, 0.0f), float2(0.5f, 0.86602497100830078f), float2(-0.5f, 0.86602497100830078f), float2(-1.0f, 0.0f), float2(-0.5f, -0.86602497100830078f), float2(0.5f, -0.86602497100830078f) } };

    float radius_0 = kernelContext_3->tone_0->occlusion_0.y;

    float2 _S31 = min(float2(_S17 / _S23, 1.0f) * float2(radius_0)  / float2((2.0f * max(abs(_S29), 0.10000000149011612f) * kernelContext_3->tone_0->occlusion_0.w)) , pixel_1 * float2(32.0f) );

#line 72
    uint i_0 = 0U;

#line 72
    float blocked_0 = 0.0f;

    for(;;)
    {

#line 74
        if(i_0 < 12U)
        {
        }
        else
        {

#line 74
            break;
        }

#line 75
        float2 _S32 = _S30[i_0 % 6U] * _S31;

#line 75
        float _S33;

#line 75
        if(i_0 < 6U)
        {

#line 75
            _S33 = 0.5f;

#line 75
        }
        else
        {

#line 75
            _S33 = 1.0f;

#line 75
        }

#line 75
        float2 sampleUv_0 = uv_2 + _S32 * float2(_S33) ;

        if(all(sampleUv_0 > (float2(0.0f) )))
        {

#line 77
            _S15 = all(sampleUv_0 < (float2(1.0f) ));

#line 77
        }
        else
        {

#line 77
            _S15 = false;

#line 77
        }

#line 77
        float blocked_1;

#line 77
        if(_S15)
        {

#line 78
            float tapDistance_0 = ((kernelContext_3->hdrScene_texture_0).sample((kernelContext_3->hdrScene_sampler_0), (sampleUv_0), level((0.0f)))).w;
            if(tapDistance_0 > 0.0f)
            {

#line 79
                float3 _S34 = contactPosition_0(sampleUv_0, tapDistance_0, kernelContext_3);
                float3 delta_0 = _S34 - _S16;
                float lengthSquared_0 = dot(delta_0, delta_0);

#line 81
                bool _S35;
                if(lengthSquared_0 > 9.99999997475242708e-07f)
                {

#line 82
                    _S35 = lengthSquared_0 < (radius_0 * radius_0);

#line 82
                }
                else
                {

#line 82
                    _S35 = false;

#line 82
                }

#line 82
                if(_S35)
                {

#line 82
                    blocked_1 = blocked_0 + saturate((dot(normal_2, delta_0) - kernelContext_3->tone_0->occlusion_0.z) / sqrt(lengthSquared_0)) * (1.0f - lengthSquared_0 / (radius_0 * radius_0));

#line 82
                }
                else
                {

#line 82
                    blocked_1 = blocked_0;

#line 82
                }

#line 79
            }
            else
            {

#line 79
                blocked_1 = blocked_0;

#line 79
            }

#line 77
        }
        else
        {

#line 77
            blocked_1 = blocked_0;

#line 77
        }

#line 74
        i_0 = i_0 + 1U;

#line 74
        blocked_0 = blocked_1;

#line 74
    }

#line 89
    return saturate(1.0f - kernelContext_3->tone_0->occlusion_0.x * (1.0f - smoothstep(32.0f, 64.0f, distance_1)) * blocked_0 / 6.0f);
}


#line 16 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraExtractBloom_0(float3 hdrColor_1, float threshold_0)
{
    float3 color_1 = max(hdrColor_1, float3(0.0f) );
    float _S36 = max(max(color_1.x, color_1.y), color_1.z);
    return color_1 * float3(max(_S36 - max(threshold_0, 0.0f), 0.0f))  / float3(max(_S36, 0.00009999999747379f)) ;
}

float3 NexoraApplyBloom_0(float3 hdrColor_2, float3 bloomColor_0, float intensity_0)
{
    float3 _S37 = float3(0.0f) ;

#line 25
    return max(hdrColor_2, _S37) + max(bloomColor_0, _S37) * float3(max(intensity_0, 0.0f)) ;
}


#line 19 "Shaders/Nexora/Common/Color.slang"
float NexoraRec709Luminance_0(float3 linearColor_0)
{
    return dot(linearColor_0, float3(0.2125999927520752f, 0.71520000696182251f, 0.07220000028610229f));
}


#line 28 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraApplyColorGrade_0(float3 color_2, float3 lift_0, float3 gain_0, float saturation_0, float contrast_0)
{

    float3 _S38 = float3(0.0f) ;

#line 31
    float3 graded_0 = max(color_2 + lift_0, _S38) * max(gain_0, _S38);
    float luminance_0 = NexoraRec709Luminance_0(graded_0);

#line 32
    float3 _S39 = float3(0.5f) ;

    return max((mix(float3(luminance_0, luminance_0, luminance_0), graded_0, float3(saturation_0) ) - _S39) * float3(contrast_0)  + _S39, _S38);
}


#line 11 "Shaders/Nexora/Common/Color.slang"
float3 NexoraLinearToSrgb_0(float3 linearColor_1)
{
    float3 color_3 = max(linearColor_1, float3(0.0f) );


    return mix(color_3 * float3(12.92000007629394531f) , float3(1.0549999475479126f)  * pow(color_3, float3(0.4166666567325592f) ) - float3(0.05499999970197678f) , step(float3(0.00313080009073019f) , color_3));
}


#line 16
struct pixelOutput_0
{
    float4 output_0 [[color(0)]];
};


#line 16
struct pixelInput_0
{
    float2 uv_3 [[user(TEXCOORD)]];
};


#line 92 "Engine/Presentation/shaders/scene_tonemap.slang"
[[fragment]] pixelOutput_0 toneFragmentMain(pixelInput_0 _S40 [[stage_in]], float4 position_0 [[position]], texture2d<float, access::sample> hdrScene_texture_1 [[texture(0)]], sampler hdrScene_sampler_1 [[sampler(0)]], ToneParameters_0 constant* tone_1 [[buffer(0)]])
{

#line 92
    thread KernelContext_0 kernelContext_4;

#line 92
    (&kernelContext_4)->hdrScene_texture_0 = hdrScene_texture_1;

#line 92
    (&kernelContext_4)->hdrScene_sampler_0 = hdrScene_sampler_1;

#line 92
    (&kernelContext_4)->tone_0 = tone_1;
    float4 _S41 = ((hdrScene_texture_1).sample((hdrScene_sampler_1), (_S40.uv_3), level((0.0f))));

#line 93
    float3 hdr_1;
    if((tone_1->antiAlias_0.z) > 0.5f)
    {

#line 94
        float3 _S42 = filterEdges_0(_S40.uv_3, _S41.xyz, &kernelContext_4);

#line 94
        hdr_1 = _S42;

#line 94
    }
    else
    {

#line 94
        hdr_1 = _S41.xyz;

#line 94
    }

#line 94
    bool _S43;
    if(((&kernelContext_4)->tone_0->focus_0.y) > 0.0f)
    {

#line 95
        _S43 = (_S41.w) > 0.0f;

#line 95
    }
    else
    {

#line 95
        _S43 = false;

#line 95
    }

#line 95
    float3 color_4;

#line 95
    uint i_1;

#line 95
    if(_S43)
    {

#line 96
        float _S44 = _S41.w;

#line 96
        float coc_0 = saturate(abs(_S44 - (&kernelContext_4)->tone_0->focus_0.x) / max(_S44, 0.00100000004749745f) * (&kernelContext_4)->tone_0->focus_0.y);
        if(coc_0 > 0.05000000074505806f)
        {

#line 98
            array<float2, int(12)> _S45 = { { float2(-1.0f, 0.0f), float2(1.0f, 0.0f), float2(0.0f, -1.0f), float2(0.0f, 1.0f), float2(-0.7070000171661377f, -0.7070000171661377f), float2(0.7070000171661377f, -0.7070000171661377f), float2(-0.7070000171661377f, 0.7070000171661377f), float2(0.7070000171661377f, 0.7070000171661377f), float2(-0.34999999403953552f, -0.34999999403953552f), float2(0.34999999403953552f, -0.34999999403953552f), float2(-0.34999999403953552f, 0.34999999403953552f), float2(0.34999999403953552f, 0.34999999403953552f) } };

#line 98
            i_1 = 0U;

#line 98
            color_4 = hdr_1;

#line 98
            float weights_0 = 1.0f;

#line 103
            for(;;)
            {

#line 103
                if(i_1 < 12U)
                {
                }
                else
                {

#line 103
                    break;
                }

#line 104
                float4 _S46 = (((&kernelContext_4)->hdrScene_texture_0).sample(((&kernelContext_4)->hdrScene_sampler_0), (_S40.uv_3 + _S45[i_1] * (&kernelContext_4)->tone_0->focus_0.zw * float2(coc_0) ), level((0.0f))));

                float weight_0 = saturate(1.0f - abs(_S46.w - _S44) / max(1.0f, _S44 * 0.25f));
                float3 sum_0 = color_4 + _S46.xyz * float3(weight_0) ;
                float weights_1 = weights_0 + weight_0;

#line 103
                i_1 = i_1 + 1U;

#line 103
                color_4 = sum_0;

#line 103
                weights_0 = weights_1;

#line 103
            }

#line 103
            hdr_1 = color_4 / float3(weights_0) ;

#line 97
        }

#line 95
    }

#line 113
    if(((&kernelContext_4)->tone_0->occlusion_0.x) > 0.0f)
    {

        float preserveHighlight_0 = saturate(max(_S41.x, max(_S41.y, _S41.z)) - 1.0f);

#line 116
        float _S47 = contactVisibility_0(_S40.uv_3, _S41.w, &kernelContext_4);

#line 116
        hdr_1 = hdr_1 * float3(mix(_S47, 1.0f, preserveHighlight_0)) ;

#line 113
    }

#line 119
    if(((&kernelContext_4)->tone_0->bloom_0.x) > 0.0f)
    {

#line 120
        float2 _S48 = (&kernelContext_4)->tone_0->bloom_0.zw;

        array<float2, int(12)> _S49 = { { float2(-1.0f, 0.0f), float2(1.0f, 0.0f), float2(0.0f, -1.0f), float2(0.0f, 1.0f), float2(-0.5f, -0.5f), float2(0.5f, -0.5f), float2(-0.5f, 0.5f), float2(0.5f, 0.5f), float2(-0.25f, 0.0f), float2(0.25f, 0.0f), float2(0.0f, -0.25f), float2(0.0f, 0.25f) } };


        float3 _S50 = float3(0.0f, 0.0f, 0.0f);

#line 125
        i_1 = 0U;

#line 125
        color_4 = _S50;
        for(;;)
        {

#line 126
            if(i_1 < 12U)
            {
            }
            else
            {

#line 126
                break;
            }

#line 127
            float3 glow_0 = color_4 + NexoraExtractBloom_0((((&kernelContext_4)->hdrScene_texture_0).sample(((&kernelContext_4)->hdrScene_sampler_0), (_S40.uv_3 + _S49[i_1] * _S48), level((0.0f)))).xyz, (&kernelContext_4)->tone_0->bloom_0.y) / float3(12.0f) ;

#line 126
            i_1 = i_1 + 1U;

#line 126
            color_4 = glow_0;

#line 126
        }

#line 126
        hdr_1 = NexoraApplyBloom_0(hdr_1, color_4, (&kernelContext_4)->tone_0->bloom_0.x);

#line 119
    }

#line 132
    float3 color_5 = saturate(NexoraApplyColorGrade_0(NexoraAcesApproximate_0(hdr_1 * float3((&kernelContext_4)->tone_0->settings_0.x) ), float3(int3(int(0)) ), float3(int3(int(1)) ), (&kernelContext_4)->tone_0->settings_0.z, (&kernelContext_4)->tone_0->settings_0.w));
    if(((&kernelContext_4)->tone_0->settings_0.y) > 0.5f)
    {

#line 133
        color_4 = NexoraLinearToSrgb_0(color_5);

#line 133
    }
    else
    {

#line 133
        color_4 = color_5;

#line 133
    }

#line 133
    pixelOutput_0 _S51 = { float4(color_4, 1.0f) };
    return _S51;
}

)NEXORA_TONE";
} // namespace Nexora::Presentation
// clang-format on
