// Generated by shaders/GenerateToneShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_tonemap_metal_vert[] = R"NEXORA_TONE(
#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 11 "Engine/Presentation/shaders/scene_tonemap.slang"
struct toneVertexMain_Result_0
{
    float4 position_0 [[position]];
    float2 uv_0 [[user(TEXCOORD)]];
};


#line 11
struct vertexInput_0
{
    float2 position_1 [[attribute(0)]];
    float2 uv_1 [[attribute(1)]];
};


#line 9
struct ToneVertex_0
{
    float4 position_2;
    float2 uv_2;
};


#line 9
[[vertex]] toneVertexMain_Result_0 toneVertexMain(vertexInput_0 _S1 [[stage_in]])
{



    thread ToneVertex_0 output_0;
    (&output_0)->position_2 = float4(_S1.position_1, 0.0f, 1.0f);



    (&output_0)->uv_2 = _S1.uv_1;

#line 19
    thread toneVertexMain_Result_0 _S2;

#line 19
    (&_S2)->position_0 = output_0.position_2;

#line 19
    (&_S2)->uv_0 = output_0.uv_2;

#line 19
    return _S2;
}

)NEXORA_TONE";
inline constexpr char scene_tonemap_metal_frag[] = R"NEXORA_TONE(
#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_0)
{
    float3 color_0 = max(hdrColor_0, float3(0.0f) );
    return saturate(color_0 * (float3(2.50999999046325684f)  * color_0 + float3(0.02999999932944775f) ) / (color_0 * (float3(2.43000006675720215f)  * color_0 + float3(0.5899999737739563f) ) + float3(0.14000000059604645f) ));
}


#line 11
float3 NexoraLinearToSrgb_0(float3 linearColor_0)
{
    float3 color_1 = max(linearColor_0, float3(0.0f) );


    return mix(color_1 * float3(12.92000007629394531f) , float3(1.0549999475479126f)  * pow(color_1, float3(0.4166666567325592f) ) - float3(0.05499999970197678f) , step(float3(0.00313080009073019f) , color_1));
}


#line 90 "core"
struct pixelOutput_0
{
    float4 output_0 [[color(0)]];
};


#line 90
struct pixelInput_0
{
    float2 uv_0 [[user(TEXCOORD)]];
};


#line 2 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneParameters_0
{
    float4 settings_0;
};


#line 6
struct KernelContext_0
{
    texture2d<float, access::sample> hdrScene_texture_0;
    sampler hdrScene_sampler_0;
    ToneParameters_0 constant* tone_0;
};


#line 24
[[fragment]] pixelOutput_0 toneFragmentMain(pixelInput_0 _S1 [[stage_in]], float4 position_0 [[position]], texture2d<float, access::sample> hdrScene_texture_1 [[texture(0)]], sampler hdrScene_sampler_1 [[sampler(0)]], ToneParameters_0 constant* tone_1 [[buffer(0)]])
{

#line 24
    thread KernelContext_0 kernelContext_0;

#line 24
    (&kernelContext_0)->hdrScene_texture_0 = hdrScene_texture_1;

#line 24
    (&kernelContext_0)->hdrScene_sampler_0 = hdrScene_sampler_1;

#line 24
    (&kernelContext_0)->tone_0 = tone_1;
    float3 color_2 = NexoraAcesApproximate_0(((hdrScene_texture_1).sample((hdrScene_sampler_1), (_S1.uv_0), level((0.0f)))).xyz * float3(tone_1->settings_0.x) );

#line 25
    float3 color_3;
    if((tone_1->settings_0.y) > 0.5f)
    {

#line 26
        color_3 = NexoraLinearToSrgb_0(color_2);

#line 26
    }
    else
    {

#line 26
        color_3 = color_2;

#line 26
    }

#line 26
    pixelOutput_0 _S2 = { float4(color_3, 1.0f) };
    return _S2;
}

)NEXORA_TONE";
} // namespace Nexora::Presentation
// clang-format on
