// Generated by shaders/GenerateToneShaders.py with Slang 2026.18.
// clang-format off
#pragma once
#include <cstdint>
namespace Nexora::Presentation {
inline constexpr char scene_tonemap_hlsl_vert[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_0 : TEXCOORD0;
};


#line 11
ToneVertex_0 toneVertexMain(float2 position_1 : POSITION, float2 uv_1 : TEXCOORD0)
{

    ToneVertex_0 output_0;
    output_0.position_0 = float4(position_1, 0.0f, 1.0f);



    output_0.uv_0 = uv_1;

    return output_0;
}

)NEXORA_TONE";
inline constexpr char scene_tonemap_hlsl_frag[] = R"NEXORA_TONE(
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 93 "core"
Texture2D<float4 > hdrScene_texture_0 : register(t0);


#line 1188 "hlsl.meta.slang"
SamplerState hdrScene_sampler_0 : register(s0);


#line 2 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneParameters_0
{
    float4 settings_0;
    float4 bloom_0;
};


#line 6
cbuffer tone_0 : register(b0)
{
    ToneParameters_0 tone_0;
}

#line 16 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraExtractBloom_0(float3 hdrColor_0, float threshold_0)
{
    float3 color_0 = max(hdrColor_0, (float3)0.0f);
    float _S1 = max(max(color_0.x, color_0.y), color_0.z);
    return color_0 * max(_S1 - max(threshold_0, 0.0f), 0.0f) / max(_S1, 0.00009999999747379f);
}

float3 NexoraApplyBloom_0(float3 hdrColor_1, float3 bloomColor_0, float intensity_0)
{
    float3 _S2 = (float3)0.0f;

#line 25
    return max(hdrColor_1, _S2) + max(bloomColor_0, _S2) * max(intensity_0, 0.0f);
}


#line 24 "Shaders/Nexora/Common/Color.slang"
float3 NexoraAcesApproximate_0(float3 hdrColor_2)
{
    float3 color_1 = max(hdrColor_2, (float3)0.0f);
    return saturate(color_1 * (2.50999999046325684f * color_1 + 0.02999999932944775f) / (color_1 * (2.43000006675720215f * color_1 + 0.5899999737739563f) + 0.14000000059604645f));
}


#line 19
float NexoraRec709Luminance_0(float3 linearColor_0)
{
    return dot(linearColor_0, float3(0.2125999927520752f, 0.71520000696182251f, 0.07220000028610229f));
}


#line 28 "Shaders/Nexora/Common/PostProcess.slang"
float3 NexoraApplyColorGrade_0(float3 color_2, float3 lift_0, float3 gain_0, float saturation_0, float contrast_0)
{

    float3 _S3 = (float3)0.0f;

#line 31
    float3 graded_0 = max(color_2 + lift_0, _S3) * max(gain_0, _S3);
    float luminance_0 = NexoraRec709Luminance_0(graded_0);

    return max((lerp(float3(luminance_0, luminance_0, luminance_0), graded_0, (float3)saturation_0) - 0.5f) * contrast_0 + 0.5f, _S3);
}


#line 11 "Shaders/Nexora/Common/Color.slang"
float3 NexoraLinearToSrgb_0(float3 linearColor_1)
{
    float3 color_3 = max(linearColor_1, (float3)0.0f);


    return lerp(color_3 * 12.92000007629394531f, 1.0549999475479126f * pow(color_3, (float3)0.4166666567325592f) - 0.05499999970197678f, step((float3)0.00313080009073019f, color_3));
}


#line 9 "Engine/Presentation/shaders/scene_tonemap.slang"
struct ToneVertex_0
{
    float4 position_0 : SV_Position;
    float2 uv_0 : TEXCOORD0;
};


#line 24
float4 toneFragmentMain(ToneVertex_0 input_0) : SV_TARGET
{

#line 25
    float3 hdr_0 = hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_0, 0.0f).xyz;

#line 25
    float3 hdr_1;
    if((tone_0.bloom_0.x) > 0.0f)
    {

#line 27
        float2 _S4 = tone_0.bloom_0.zw;

        float2  _S5[int(12)] = { float2(-1.0f, 0.0f), float2(1.0f, 0.0f), float2(0.0f, -1.0f), float2(0.0f, 1.0f), float2(-0.5f, -0.5f), float2(0.5f, -0.5f), float2(-0.5f, 0.5f), float2(0.5f, 0.5f), float2(-0.25f, 0.0f), float2(0.25f, 0.0f), float2(0.0f, -0.25f), float2(0.0f, 0.25f) };


        float3 _S6 = float3(0.0f, 0.0f, 0.0f);

#line 32
        uint i_0 = 0U;

#line 32
        hdr_1 = _S6;
        [unroll]
        for(;;)
        {

#line 33
            if(i_0 < 12U)
            {
            }
            else
            {

#line 33
                break;
            }

#line 34
            float3 glow_0 = hdr_1 + NexoraExtractBloom_0(hdrScene_texture_0.SampleLevel(hdrScene_sampler_0, input_0.uv_0 + _S5[i_0] * _S4, 0.0f).xyz, tone_0.bloom_0.y) / 12.0f;

#line 33
            i_0 = i_0 + 1U;

#line 33
            hdr_1 = glow_0;

#line 33
        }

#line 33
        hdr_1 = NexoraApplyBloom_0(hdr_0, hdr_1, tone_0.bloom_0.x);

#line 26
    }
    else
    {

#line 26
        hdr_1 = hdr_0;

#line 26
    }

#line 39
    float3 color_4 = saturate(NexoraApplyColorGrade_0(NexoraAcesApproximate_0(hdr_1 * tone_0.settings_0.x), float3((int3)int(0)), float3((int3)int(1)), tone_0.settings_0.z, tone_0.settings_0.w));

#line 39
    float3 color_5;
    if((tone_0.settings_0.y) > 0.5f)
    {

#line 40
        color_5 = NexoraLinearToSrgb_0(color_4);

#line 40
    }
    else
    {

#line 40
        color_5 = color_4;

#line 40
    }
    return float4(color_5, 1.0f);
}

)NEXORA_TONE";
} // namespace Nexora::Presentation
// clang-format on
