include(NexoraTarget)
add_library(NexoraWindow ${NEXORA_MODULE_LIBRARY_TYPE} src/Window.cpp)
add_library(Nexora::Window ALIAS NexoraWindow)
target_include_directories(NexoraWindow PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>")
target_link_libraries(NexoraWindow PUBLIC Nexora::Core)
target_compile_definitions(NexoraWindow PRIVATE NEXORA_WINDOW_EXPORTS)
if(NEXORA_LINK_MODE STREQUAL "Monolithic")
  target_compile_definitions(NexoraWindow PUBLIC NEXORA_WINDOW_STATIC=1)
endif()
nexora_apply_defaults(NexoraWindow)
