include(NexoraTarget)
add_library(NexoraAI ${NEXORA_MODULE_LIBRARY_TYPE} src/AI.cpp)
add_library(Nexora::AI ALIAS NexoraAI)
target_include_directories(NexoraAI PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>")
target_link_libraries(NexoraAI PUBLIC Nexora::Core)
target_compile_definitions(NexoraAI PRIVATE NEXORA_AI_EXPORTS)
if(NEXORA_LINK_MODE STREQUAL "Monolithic")
  target_compile_definitions(NexoraAI PUBLIC NEXORA_AI_STATIC=1)
endif()
nexora_apply_defaults(NexoraAI)
