add_executable(NexoraProjectPlayer main.cpp)
target_link_libraries(NexoraProjectPlayer PRIVATE Nexora::Runtime)
if(NEXORA_ENABLE_PROJECT_PLAYER_NATIVE)
  target_link_libraries(NexoraProjectPlayer PRIVATE Nexora::Presentation)
  target_compile_definitions(NexoraProjectPlayer PRIVATE NEXORA_PROJECT_PLAYER_NATIVE=1)
endif()
if(MINGW)
  target_link_options(NexoraProjectPlayer PRIVATE -municode)
endif()
nexora_apply_defaults(NexoraProjectPlayer)
