#!/usr/bin/env python3
"""Embed native PBR entries compiled from the shared Slang library (pinned 2026.18)."""
import argparse
from pathlib import Path
import re
import struct
import subprocess
import tempfile


def embed_hlsl_source(name: str, source: str) -> str:
    # MSVC limits an individual literal to 16 KiB. Concatenation preserves the
    # exact compiler output, including its leading newline and final NUL.
    source = '\n' + source
    if ')NEXORA_PBR"' in source:
        raise ValueError('Generated source contains the raw-string delimiter')
    if len(source.encode('utf-8')) <= 8192:
        return f'inline constexpr char {name}[] = R"NEXORA_PBR({source})NEXORA_PBR";\n'
    # 2048 Unicode characters occupy at most 8192 UTF-8 bytes.
    chunks = [source[start:start + 2048] for start in range(0, len(source), 2048)]
    literals = '\n'.join(f'R"NEXORA_PBR({chunk})NEXORA_PBR"' for chunk in chunks)
    return f'inline constexpr char {name}[] =\n{literals};\n'


def generate(compiler: str, check: bool) -> None:
    root = Path(__file__).resolve().parents[3]
    shaders = root / 'Engine/Presentation/shaders'
    version = subprocess.run([compiler, '-v'], check=True, text=True, capture_output=True)
    if not re.search(r'2026\.18(?:\D|$)', version.stdout + version.stderr):
        raise SystemExit('Native PBR generation requires Slang 2026.18')
    targets = [('spirv', 'Vulkan'), ('hlsl', 'Hlsl'), ('metal', 'Metal')]
    with tempfile.TemporaryDirectory(prefix='nexora-pbr-shaders-') as directory:
        for target, label in targets:
            text = '// Generated by shaders/GeneratePbrShaders.py with Slang 2026.18.\n'
            text += '// clang-format off\n#pragma once\n#include <cstdint>\nnamespace Nexora::Presentation {\n'
            for stage, entry in [('vert', 'pbrVertexMain'), ('frag', 'pbrFragmentMain'),
                                 ('shadow_frag', 'shadowFragmentMain')]:
                output = Path(directory) / f'{stage}.{target}'
                command = [compiler, 'Engine/Presentation/shaders/scene_pbr.slang', '-I', 'Shaders',
                           '-target', target, '-entry', entry, '-o', str(output)]
                if target == 'spirv':
                    command += ['-profile', 'glsl_450', '-DNEXORA_VULKAN=1']
                elif target == 'hlsl':
                    command += ['-profile', 'sm_5_0']
                subprocess.run(command, cwd=root, check=True)
                name = f'scene_pbr_{target}_{stage}'
                if target == 'spirv':
                    data = output.read_bytes()
                    if len(data) % 4 or struct.unpack_from('<I', data)[0] != 0x07230203:
                        raise SystemExit('Invalid generated SPIR-V')
                    words = struct.unpack(f'<{len(data)//4}I', data)
                    text += f'inline constexpr std::uint32_t {name}[] = {{\n'
                    for start in range(0, len(words), 8):
                        text += '  ' + ', '.join(f'0x{x:08x}' for x in words[start:start+8]) + ',\n'
                    text += '};\n'
                else:
                    source = output.read_text()
                    # Source diagnostics are reproducible repository-relative compiler paths.
                    if ')NEXORA_PBR"' in source:
                        raise SystemExit('Generated source contains the raw-string delimiter')
                    if target == 'hlsl':
                        text += embed_hlsl_source(name, source)
                    else:
                        text += f'inline constexpr char {name}[] = R"NEXORA_PBR(\n{source})NEXORA_PBR";\n'
            text += '} // namespace Nexora::Presentation\n// clang-format on\n'
            path = root / f'Engine/Presentation/src/ScenePbr{label}Shaders.h'
            if check:
                if not path.is_file() or path.read_text() != text:
                    raise SystemExit(f'Embedded PBR shader differs: {path}')
            else:
                path.write_text(text)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compiler', default='slangc')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generate(args.compiler, args.check)
