#!/usr/bin/env python3
"""Regenerate embedded Vulkan SPIR-V; no shader compiler is required at runtime."""
from pathlib import Path
import argparse
import struct
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('--compiler', default='glslangValidator')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parent
for family in ('scene', 'ui'):
    result = '// Generated by shaders/GenerateShaders.py using glslangValidator -V.\n'
    result += '#pragma once\n#include <cstdint>\nnamespace Nexora::Presentation {\n'
    with tempfile.TemporaryDirectory() as directory:
        for stage in ('vert', 'frag'):
            binary = Path(directory) / 'shader.spv'
            subprocess.run([args.compiler, '-V', str(root / f'{family}.{stage}'), '-o', str(binary)], check=True)
            data = binary.read_bytes()
            words = struct.unpack(f'<{len(data)//4}I', data)
            name = f'{family}_{stage}'
            result += f'inline constexpr std::uint32_t {name}[] = {{\n'
            for start in range(0, len(words), 8):
                result += '  ' + ', '.join(f'0x{x:08x}' for x in words[start:start+8]) + ',\n'
            result += '};\n'
    result += '} // namespace Nexora::Presentation\n'
    target = root.parent / 'src' / f'{family.title()}VulkanShaders.h'
    if args.check:
        if target.read_text() != result:
            raise SystemExit(f'Embedded shader differs from source: {target}')
    else:
        target.write_text(result)
