#!/usr/bin/env python3
"""Embed native PBR entries compiled from the shared Slang library (pinned 2026.18)."""
import argparse
from pathlib import Path
import re
import struct
import subprocess
import tempfile


# MSVC rejects a single string literal longer than 16380 bytes (C2026). Adjacent literals are
# concatenated, so long sources are emitted as several raw-string pieces split at line boundaries.
RAW_STRING_PIECE_LIMIT = 12000


def emit_raw_string(name, source):
    pieces, current, size = [], [], 0
    for line in source.splitlines(keepends=True):
        line_size = len(line.encode('utf-8'))
        if line_size > RAW_STRING_PIECE_LIMIT:
            raise SystemExit(f'Generated source line exceeds the string piece limit: {name}')
        if current and size + line_size > RAW_STRING_PIECE_LIMIT:
            pieces.append(''.join(current))
            current, size = [], 0
        current.append(line)
        size += line_size
    pieces.append(''.join(current))
    text = f'inline constexpr char {name}[] = R"NEXORA_PBR(\n{pieces[0]})NEXORA_PBR"'
    for piece in pieces[1:]:
        text += f'\n    R"NEXORA_PBR({piece})NEXORA_PBR"'
    return text + ';\n'


def generate(compiler: str, check: bool) -> None:
    root = Path(__file__).resolve().parents[3]
    shaders = root / 'Engine/Presentation/shaders'
    version = subprocess.run([compiler, '-v'], check=True, text=True, capture_output=True)
    if not re.search(r'2026\.18(?:\D|$)', version.stdout + version.stderr):
        raise SystemExit('Native PBR generation requires Slang 2026.18')
    targets = [('spirv', 'Vulkan'), ('hlsl', 'Hlsl'), ('metal', 'Metal')]
    with tempfile.TemporaryDirectory(prefix='nexora-pbr-shaders-') as directory:
        for target, label in targets:
            text = '// Generated by shaders/GeneratePbrShaders.py with Slang 2026.18.\n'
            text += '// clang-format off\n#pragma once\n#include <cstdint>\nnamespace Nexora::Presentation {\n'
            for stage, entry in [('vert', 'pbrVertexMain'), ('frag', 'pbrFragmentMain'),
                                 ('shadow_frag', 'shadowFragmentMain')]:
                output = Path(directory) / f'{stage}.{target}'
                command = [compiler, 'Engine/Presentation/shaders/scene_pbr.slang', '-I', 'Shaders',
                           '-target', target, '-entry', entry, '-o', str(output)]
                if target == 'spirv':
                    command += ['-profile', 'glsl_450', '-DNEXORA_VULKAN=1']
                elif target == 'hlsl':
                    command += ['-profile', 'sm_5_0']
                subprocess.run(command, cwd=root, check=True)
                name = f'scene_pbr_{target}_{stage}'
                if target == 'spirv':
                    data = output.read_bytes()
                    if len(data) % 4 or struct.unpack_from('<I', data)[0] != 0x07230203:
                        raise SystemExit('Invalid generated SPIR-V')
                    words = struct.unpack(f'<{len(data)//4}I', data)
                    text += f'inline constexpr std::uint32_t {name}[] = {{\n'
                    for start in range(0, len(words), 8):
                        text += '  ' + ', '.join(f'0x{x:08x}' for x in words[start:start+8]) + ',\n'
                    text += '};\n'
                else:
                    source = output.read_text()
                    # Source diagnostics are reproducible repository-relative compiler paths.
                    if ')NEXORA_PBR"' in source:
                        raise SystemExit('Generated source contains the raw-string delimiter')
                    text += emit_raw_string(name, source)
            text += '} // namespace Nexora::Presentation\n// clang-format on\n'
            path = root / f'Engine/Presentation/src/ScenePbr{label}Shaders.h'
            if check:
                if not path.is_file() or path.read_text() != text:
                    raise SystemExit(f'Embedded PBR shader differs: {path}')
            else:
                path.write_text(text)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compiler', default='slangc')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generate(args.compiler, args.check)
