#!/usr/bin/env python3
"""Regenerate private Vulkan scene SPIR-V with glslangValidator and spirv-val."""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
source = Path(__file__).resolve().parent
output = source.parent / "src" / "SceneVulkanShaders.h"
header = "// Generated by shaders/GenerateSceneShaders.py; do not edit.\n#pragma once\n#include <cstdint>\nnamespace Nexora::Presentation {\n"
with tempfile.TemporaryDirectory() as temporary:
    for stage in ("vert", "frag"):
        binary = Path(temporary) / f"scene.{stage}.spv"
        subprocess.run(["glslangValidator", "-V", "--target-env", "vulkan1.1",
                        str(source / f"Scene.{stage}"), "-o", str(binary)], check=True)
        subprocess.run(["spirv-val", "--target-env", "vulkan1.1", str(binary)], check=True)
        data = binary.read_bytes()
        words = struct.unpack(f"<{len(data) // 4}I", data)
        header += f"inline constexpr std::uint32_t Scene{stage.title()}Spirv[] = {{\n"
        for offset in range(0, len(words), 8):
            header += "  " + ", ".join(f"0x{word:08x}" for word in words[offset:offset + 8]) + ",\n"
        header += "};\n"
header += "} // namespace Nexora::Presentation\n"
header = subprocess.run(["clang-format", "--assume-filename", str(output)],
                        input=header, capture_output=True, text=True, check=True).stdout
if args.check:
    if output.read_text() != header:
        raise SystemExit("SceneVulkanShaders.h is stale; regenerate the private scene shaders")
else:
    output.write_text(header)
